version: '3.2'

services:
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.4.0
    networks:
      net-guacamole:
    restart: always
    volumes:
    - ./drive:/drive
    - ./record:/record

  postgres:
    container_name: postgres_guacamole
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: MYPASSWORD
      POSTGRES_USER: guacamole_user
    image: postgres:13
    networks:
      net-guacamole:
    restart: always
    volumes:
    - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    - ./data:/var/lib/postgresql/data
    # ports:
    # - 5432:5432

  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: MYPASSWORD
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole:1.4.0
    links:
    - guacd
    networks:
      net-guacamole:
    ports:
    - 8080:8080
    restart: always
    volumes:
      - ./guacamole-scripts/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp
      - ./guacamole-scripts/start.sh:/opt/guacamole/bin/start.sh

networks:
  net-guacamole:
    driver: bridge
